[APP]
ENVIRONMENT = "test"
DEBUG = true
# Only accept True or False

[MYSQL]
USERNAME = "root"
PASSWORD = ""
HOST = "127.0.0.1"
PORT = 3306
DATABASE = "abandon"

[AUTH]
SALT = "chifanlema"
KEY = "chile"
EXPIRED_HOUR = 72